name: publish
on: [push]

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/deselikem/hello-docker-gcr-demo:latest
          
      - name: Run the hello-docker image (optional, usually not needed in CI)
        run: |
          docker run ghcr.io/deselikem/hello-docker-gcr-demo:latest

      - name: Push the hello-docker Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/deselikem/hello-docker-gcr-demo:latest
